# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - uses: samin/mysql-action@v1.3
      with:
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql database: 'routiin2'
        mysql user: ${{secrets.MYSQL_USER}} 
        mysql password: ${{ secrets.MYSQL_PASSWORD }}      
    - name: Build with Maven
      run: mvn package -DFB_CLIENT_SECRET=${{ secrets.FB_CLIENT_SECRET }} -DFB_CLIENT_ID=${{ secrets.FB_CLIENT_ID }} -DGOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} -DGOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} -DMYSQL_URL=${{ secrets.MYSQL_URL }} -DMYSQL_USER=${{ secrets.MYSQL_USER }} -DMYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} -DSHOW_SQL=${{ secrets.SHOW_SQL_PROD }} -DSERVER_PORT=${{ secrets.SERVER_PORT_PROD }} -DTOKEN_SECRET=${{ secrets.TOKEN_SECRET }}
    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "target/routiin-0.0.1.jar"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
    - name: Restart Routiin Server App
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo systemctl restart routiin.service
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
    
  
  
